apiVersion: v1
data:
  image: helloworld:v1 # {"$ref":"#/definitions/io.k8s.cli.setters.image"}
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/function: |
      container: {image: generate}
  name: generate
